(package "vc-refresh"
         "0.1.0"
         "Refresh vc-state in certain events for better UX")

(website-url "https://github.com/jcs-elpa/vc-refresh")
(keywords "vc")

(package-file "vc-refresh.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
